import 'package:flutter/cupertino.dart';

import '../../../../resources/resources.dart';
import '../model/news_model.dart';

class NewsProvider extends ChangeNotifier {
  update() {
    notifyListeners();
  }

  List<NewsModel> newsList = [
    NewsModel(
      coinImage: R.images.bitcoin,
      coinName: "Bitcoin",
      coinType: "Btc",
      coinDescription: R.dummyData.longerText,
      coinHeading: R.dummyData.bulletText,
      createdAt: DateTime(2023,7,7,10,5),
    ),
    NewsModel(
      coinImage: R.images.ethereum,
      coinName: "Ethereum",
      coinType: "Bitcoin",
      coinDescription: R.dummyData.longerText,
      coinHeading: R.dummyData.bulletText,
      createdAt: DateTime(2023,7,7,10,5),
    ),
    NewsModel(
      coinImage: R.images.altcoin,
      coinName: "Analytics",
      coinType: "Btc",
      coinDescription: R.dummyData.longerText,
      coinHeading: R.dummyData.bulletText,
      createdAt: DateTime(2023,7,7,10,5),
    ),
    NewsModel(
      coinImage: R.images.memecoin,
      coinName: "Exchange",
      coinType: "Btc",
      coinDescription: R.dummyData.longerText,
      coinHeading: R.dummyData.bulletText,
      createdAt: DateTime(2023,7,7,10,5),
    ),
    NewsModel(
      coinImage: R.images.defi,
      coinName: "Altcoins",
      coinType: "Btc",
      coinDescription: R.dummyData.longerText,
      coinHeading: R.dummyData.bulletText,
      createdAt: DateTime(2023,7,7,10,5),
    ),
    NewsModel(
      coinImage: R.images.regulation,
      coinName: "Legal",
      coinType: "Btc",
      coinDescription: R.dummyData.longerText,
      coinHeading: R.dummyData.bulletText,
      createdAt: DateTime(2023,7,7,10,5),
    ),
    // NewsModel(
    //   coinImage: R.images.adoption,
    //   coinName: "NFT",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.mining,
    //   coinName: "Blockchain",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.metaverse,
    //   coinName: "GameFi",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.ai,
    //   coinName: "Finance",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Other",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Security",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Mining",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Economy",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Banking",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "World",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Markets",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.bitcoin,
    //   coinName: "Bitcoin",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.ethereum,
    //   coinName: "Ethereum",
    //   coinType: "Bitcoin",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.altcoin,
    //   coinName: "Analytics",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.memecoin,
    //   coinName: "Exchange",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.defi,
    //   coinName: "Altcoins",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.regulation,
    //   coinName: "Legal",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.business,
    //   coinName: "Metaverse",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.adoption,
    //   coinName: "NFT",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.mining,
    //   coinName: "Blockchain",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.metaverse,
    //   coinName: "GameFi",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.ai,
    //   coinName: "Finance",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Other",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Security",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Mining",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Economy",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Banking",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "World",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Markets",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.ai,
    //   coinName: "Finance",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Other",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Security",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Mining",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Economy",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Banking",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "World",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.web3,
    //   coinName: "Markets",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.bitcoin,
    //   coinName: "Bitcoin",
    //   coinType: "Btc",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
    // NewsModel(
    //   coinImage: R.images.ethereum,
    //   coinName: "Ethereum",
    //   coinType: "Bitcoin",
    //   coinDescription: R.dummyData.longerText,
    //   coinHeading: R.dummyData.bulletText,
    // ),
  ];
}
